name: gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.x'
    - name: Publish
      run: dotnet publish --configuration Release --output build AnimePomodoro
    - name: Fix base href
      run: sed -i 's|<base href="/" />|<base href="/AnimePomodoro/" />|' build/wwwroot/index.html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: build/wwwroot
        clean: true
